name: C++ CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: actions/setup-cmake@v2
        with:
          cmake-version: "3.22"

      - name: Clone Google Test
        run: |
          mkdir third_party
          git clone --branch release-1.11.0 --depth 1 https://github.com/google/googletest.git third_party/googletest

      - name: Make scripts executable
        run: |
          chmod +x scripts/*.sh

      - name: Build
        run: ./scripts/build_script.sh

      - name: Run tests
        run: ./scripts/run_tests_script.sh
