#Taken from: https://github.com/GHF/googletest-ci/blob/dev/.github/workflows/ci-cmake_tests.yml
name: CMake Tests

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Clone Google Test
        run: |
          mkdir third_party
          git clone --branch release-1.11.0 --depth 1 https://github.com/google/googletest.git third_party/googletest

      - name: Configure CMake
        run: cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build .

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: GTEST_OUTPUT=xml:test-results/ GTEST_COLOR=1 ctest -V

      # - name: Upload test results
      #   uses: actions/upload-artifact@v2
      #   if: failure()
      #   with:
      #     name: test_results_xml
      #     path: ${{runner.workspace}}/build/test-results/**/*.xml
